// Code generated by MockGen. DO NOT EDIT.
// Source: downloader/internal/domain (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_repository.go -package=mocks downloader/internal/domain Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "downloader/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetFileContent mocks base method.
func (m *MockRepository) GetFileContent(arg0 context.Context, arg1, arg2 int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileContent", arg0, arg1, arg2)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileContent indicates an expected call of GetFileContent.
func (mr *MockRepositoryMockRecorder) GetFileContent(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileContent", reflect.TypeOf((*MockRepository)(nil).GetFileContent), arg0, arg1, arg2)
}

// CreateDownloadAndFiles mocks base method.
func (m *MockRepository) CreateDownloadAndFiles(arg0 context.Context, arg1 *domain.DownloadTask) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDownloadAndFiles", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDownloadAndFiles indicates an expected call of CreateDownloadAndFiles.
func (mr *MockRepositoryMockRecorder) CreateDownloadAndFiles(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDownloadAndFiles", reflect.TypeOf((*MockRepository)(nil).CreateDownloadAndFiles), arg0, arg1)
}

// GetDownload mocks base method.
func (m *MockRepository) GetDownload(arg0 context.Context, arg1 int) (domain.DownloadTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDownload", arg0, arg1)
	ret0, _ := ret[0].(domain.DownloadTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDownload indicates an expected call of GetDownload.
func (mr *MockRepositoryMockRecorder) GetDownload(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDownload", reflect.TypeOf((*MockRepository)(nil).GetDownload), arg0, arg1)
}

// UpdateDownloadStatus mocks base method.
func (m *MockRepository) UpdateDownloadStatus(arg0 context.Context, arg1 int, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDownloadStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDownloadStatus indicates an expected call of UpdateDownloadStatus.
func (mr *MockRepositoryMockRecorder) UpdateDownloadStatus(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDownloadStatus", reflect.TypeOf((*MockRepository)(nil).UpdateDownloadStatus), arg0, arg1, arg2)
}

// UpdateFile mocks base method.
func (m *MockRepository) UpdateFile(arg0 context.Context, arg1, arg2 int, arg3 string, arg4 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFile", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFile indicates an expected call of UpdateFile.
func (mr *MockRepositoryMockRecorder) UpdateFile(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFile", reflect.TypeOf((*MockRepository)(nil).UpdateFile), arg0, arg1, arg2, arg3, arg4)
}
