// Code generated by MockGen. DO NOT EDIT.
// Source: downloader/internal/domain (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_repository.go -package=mocks downloader/internal/domain Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "downloader/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetFile mocks base method.
func (m *MockRepository) GetFile(arg0 context.Context, arg1, arg2 int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", arg0, arg1, arg2)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockRepositoryMockRecorder) GetFile(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockRepository)(nil).GetFile), arg0, arg1, arg2)
}

// RecieveDownload mocks base method.
func (m *MockRepository) RecieveDownload(arg0 context.Context, arg1 int) (domain.DownloadTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecieveDownload", arg0, arg1)
	ret0, _ := ret[0].(domain.DownloadTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecieveDownload indicates an expected call of RecieveDownload.
func (mr *MockRepositoryMockRecorder) RecieveDownload(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecieveDownload", reflect.TypeOf((*MockRepository)(nil).RecieveDownload), arg0, arg1)
}

// SaveFile mocks base method.
func (m *MockRepository) SaveFile(arg0 context.Context, arg1, arg2 int, arg3 string, arg4 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFile", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFile indicates an expected call of SaveFile.
func (mr *MockRepositoryMockRecorder) SaveFile(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFile", reflect.TypeOf((*MockRepository)(nil).SaveFile), arg0, arg1, arg2, arg3, arg4)
}

// TaskCreation mocks base method.
func (m *MockRepository) TaskCreation(arg0 context.Context, arg1 *domain.DownloadTask) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskCreation", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TaskCreation indicates an expected call of TaskCreation.
func (mr *MockRepositoryMockRecorder) TaskCreation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskCreation", reflect.TypeOf((*MockRepository)(nil).TaskCreation), arg0, arg1)
}

// UpdateStatus mocks base method.
func (m *MockRepository) UpdateStatus(arg0 context.Context, arg1 int, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRepositoryMockRecorder) UpdateStatus(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRepository)(nil).UpdateStatus), arg0, arg1, arg2)
}
